### ISSUE TITLE
Unable to determine year from 00texlive.config

### ISSUE THREAD

**Issue by suhlatwork** [amaxwell/tlutility#32]
Hi,

I have a somewhat odd problem with TeX Live Utility. Occasionally no URL is displayed in the repository URL bar, and trying to set one by clicking the Home button will lead to an internal error with an uncaught exception. If the program is restarted immediately, the repository URL is (most probably) displayed, and if it worked once, it will also work the next times (for at least a couple of minutes).

Looking into the logs I found the message `Unable to determine year from 00texlive.config`, which seems to be caused by `parse_tlpdb.py` being unable to parse a downloaded TeX Live database:
```
2015-10-20 15:17:09 +0000 Notice -[TLMDatabase texliveYear][97335]	Parsing the database from this repository failed with the following error: Traceback (most recent call last):
  File "/Applications/TeX Live Utility.app/Contents/MacOS/parse_tlpdb.py", line 452, in <module>
    all_packages, index_map = packages_from_tlpdb(flat_tlpdb)
  File "/Applications/TeX Live Utility.app/Contents/MacOS/parse_tlpdb.py", line 293, in packages_from_tlpdb
    assert "size" in attrs, "missing size for %s : %s" % (package.name, key)
AssertionError: missing size for adhocfilelist.x86_64-darwin : binfiles

2015-10-20 15:17:09 +0000 Notice -[TLMDatabase texliveYear][97335]	The database can be viewed with a text editor at "/var/folders/lg/6ksc01wj14383sjx9c6cb2v40000gn/T/6ECBCA8C-4863-470F-A472-B3B54EDA5041"
```

Indeed the downloaded database is cut short in the middle of an entry which then cannot be parsed correctly:
```
name adhocfilelist.x86_64-darwin
category Package
revision 28038
shortdesc x86_64-darwin files of adhocfilelist
containersize 344
containermd5 280be4915056f5a79e3feb95eaace5ab
binfiles arch=x86_64-darwi
```
(In fact simply pasting this into a text file and running `parse_tlpdb.py` on this file reproduces the issue.)

This is the information concerning the download in the log for a failed attempt to start TeX Live Utility:
```
2015-10-20 15:17:09 +0000 Notice -[TLMDatabase _downloadDatabaseHead][97335]	Downloading at least 2048 bytes of tlpdb for a version check…
2015-10-20 15:17:09 +0000 Notice -[TLMDatabase _downloadDatabaseHead][97335]	Downloaded 65536 bytes of tlpdb for version check
```
For working attempts, typically more bytes (either 524288 or 327680 or 196608 or 9668390 bytes) are downloaded.

This issue first occurred after updating TeX Live Utility to 1.23 (probably related to commit b3a36621606ce8d1968a139e77e737d05ff57790).

**Comment by amaxwell** [comment]
Thanks, this is a great bug report; it's been present for a long time, but this code path is likely to be hit more frequently now because of the change that you pointed out. I guess I'll add a way to let the parser know that it can ignore partial entries.

**Comment by amaxwell** [comment]
This should be fixed in the latest beta.

**Comment by suhlatwork** [comment]
Thanks, that also fixes the issue for me.
